# Site settings
title: Esther Leytush
email: eleytush@gmail.com

url: "https://estherleytush.com"
baseurl: ""

include: ['_static']

me:
  role: 'Software Engineer'
  company: 'Betterment'
  company_url: "https://www.betterment.com/invite/estherleytush"

resume:
  download_url: esther_leytush_software_engineer_resume.pdf
