version: 2
jobs:
  build:
    docker:
      # CircleCI maintains a library of pre-built images: https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/ruby:2.4-node

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Ruby dependencies
          command: bundle install
      - run:
          name: Node dependencies
          command: sudo npm install -g firebase-tools
      - run:
          name: Build
          command: bundle exec jekyll build --verbose
      - run:
          name: Deploy
          command: firebase deploy --token=$FIREBASE_TOKEN --non-interactive
