version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.2-node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Ruby dependencies
          command: bundle install
      - run:
          name: Node dependencies
          command: sudo npm install -g firebase-tools
      - run:
          name: Jekyll build
          command: bundle exec jekyll build --verbose
      - run:
          name: Firebase functions install
          command: cd functions && npm install
      - run:
          name: Firebnase deploy
          command: firebase deploy --token=$FIREBASE_TOKEN --non-interactive

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
